# Generated by Django 5.0.3 on 2024-03-28 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.IntegerField()),
                ('kurs', models.IntegerField()),
                ('talaba_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('tafsilotlar', models.TextField()),
                ('tugallangan', models.BooleanField(default=False)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.talaba')),
            ],
        ),
    ]
